$(document).ready(function(){
    $("#nav-about").click(function(){
        $(".header").hide();
         $(".text-center").hide();
          $(".container").hide();
           $(".about").show();
            $(".pontos-turisticos").hide();
             $(".restaurantes-bares").hide();
              $(".cinemas").hide();
    });

    $("#nav-home").click(function(){
        $(".header").show();
         $(".text-center").show();
          $(".container").show();
           $(".about").hide();
            $(".pontos-turisticos").hide();
             $(".restaurantes-bares").hide();
              $(".cinemas").hide();
    });

    $("#dropdown-turismo").click(function(){
        $(".header").hide();
         $(".text-center").hide();
          $(".container").hide();
           $(".about").hide();
            $(".pontos-turisticos").show();
             $(".restaurantes-bares").hide();
              $(".cinemas").hide();
    });

    $("#pontosTuristicos").click(function(){
        $(".header").hide();
         $(".text-center").hide();
          $(".container").hide();
           $(".about").hide();
            $(".pontos-turisticos").show();
             $(".restaurantes-bares").hide();
              $(".cinemas").hide();
    });

    $("#dropdown-restaurantes").click(function(){
        $(".header").hide();
         $(".text-center").hide();
          $(".container").hide();
           $(".about").hide();
            $(".pontos-turisticos").hide();
             $(".restaurantes-bares").show();
              $(".cinemas").hide();
    });

    $("#card-restaurantes").click(function(){
        $(".header").hide();
         $(".text-center").hide();
          $(".container").hide();
           $(".about").hide();
            $(".pontos-turisticos").hide();
             $(".restaurantes-bares").show();
              $(".cinemas").hide();
    });

    $("#dropdown-cinemas").click(function(){
        $(".header").hide();
         $(".text-center").hide();
          $(".container").hide();
           $(".about").hide();
            $(".pontos-turisticos").hide();
             $(".restaurantes-bares").hide();
              $(".cinemas").show();
    });
});